name: Deploy to GitHub

on:
  workflow_call:
    inputs:
      name:
        description: Name of the product released
        required: true
        type: string
      version:
        description: Version of the product released
        required: true
        type: string
      artifact:
        description: Name of the artifact to upload
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: ${{ inputs.name }}-${{ inputs.version }}
    steps:
      - name: Download Build
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact }}
          path: release-files/

      - name: Zip Build
        run: |
          apt update
          apt install zip

          cd release-files
          zip -r "../${{ env.RELEASE_NAME }}.zip" .
          cd -

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ inputs.version }}
          tag_name: ${{ inputs.version }}
          files: ${{ env.RELEASE_NAME }}.zip
          token: ${{ secrets.personal_access_token }}